---
title: "age_morbidity_countries"
author: "Gabriel Burcea"
date: "14/09/2020"
output: word_document
---




```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
library(tidyverse)
library(magrittr)
```



```{r sympt-pos}

data_categ_nosev <- readr::read_csv("/Users/gabrielburcea/rprojects/data/your.md/cleaned_data_18_08_2020_fully_cleaned_uniq_comorb.csv")

data_categ_covid <- data_categ_nosev %>%
  dplyr::filter(covid_tested != 'none') %>%
  dplyr::mutate(status_cv = dplyr::case_when(covid_tested == 'showing symptoms' ~ 0,
                                             covid_tested == 'positive' ~ 1)) %>%
  tidyr::drop_na()

```


How many male and female we have in our dataset? There are 5083 male accounting for 53 percent whilst female are 4321 accounting for 45 percent. Also, we have very low percent of other group.
```{r, gender-numbers}
gender_tb <- data_categ_covid %>%
  dplyr::select(id, gender) %>%
  dplyr::group_by(gender) %>%
  dplyr::tally() %>%
  dplyr::mutate(percent = n/sum(n)*100)

knitr::kable(gender_tb)
```


```{r, gender-pie, echo=F, results= 'asis', fig.height=5, fig.width=7}



bp <- ggplot2::ggplot(gender_tb, ggplot2::aes(x = "", y = percent, fill = gender)) + 
  ggplot2::geom_bar(width = 1, stat = "identity")

pie <- bp + ggplot2::coord_polar("y", start = 0) + 
  ggplot2::scale_fill_brewer(palette = "Blues") +
  ggplot2::theme(axis.text.x = ggplot2::element_blank())

pie
```
