---
title: "22092020_descriptives_phillipines"
author: "Gabriel Burcea"
date: "25/09/2020"
output: word_document
---
```{r}
phillipines_data <- read_csv("/Users/gabrielburcea/rprojects/data/your.md/phillipines_data.csv")
```



#Symptoms across age band (20-39; 40-59, 60+)

```{r, symptoms_positive_plot, fig.height=5, fig.width=9}

sympt_pos_age_band <- cvindia::sympt_positive_age_band(data = phillipines_data, start_date= as.Date("2020-04-09"), end_date = as.Date("2020-09-01"), plot_chart = TRUE)


sympt_pos_age_band 

```

#Symptoms across age band (20-39; 40-59, 60+)
```{r, symptoms_positive_numbers, fig.height=5, fig.width=9}

sympt_pos_age_band <- cvindia::sympt_positive_age_band(data = phillipines_data, start_date= as.Date("2020-04-09"), end_date = as.Date("2020-09-01"), 
                                                       plot_chart = FALSE )


sympt_pos_age_band <- sympt_pos_age_band %>%
  arrange(desc(percentage)) %>% top_n(5)

knitr::kable(sympt_pos_age_band)

```


#Comorbidities across age band (20-39; 40-59, 60+)

```{r, comorbidities_age_band, fig.height=5, fig.width=9}


comorb_age_band_plot <- cvindia::comorbidities_age_band(data, start_date = as.Date("2020-04-19"), end_date = as.Date("2020-09-01"), plot_chart = TRUE)

comorb_age_band_plot

```



#Comorbidities across age band (20-39; 40-59, 60+)

```{r, comorbidities_age_band_numbers, fig.height=5, fig.width=9 }

comorb_age_band_numbers <-  cvindia::comorbidities_age_band(phillipines_data, start_date = as.Date("2020-04-19"), end_date = as.Date("2020-09-01"), plot_chart = FALSE)

comorb_age_band_numbers

comorb_age_band_numbers <- comorb_age_band_numbers %>%
  arrange(desc(percentage)) %>% top_n(5)


knitr::kable(comorb_age_band_numbers)

```


#Gender and age band 20-39

```{r, age_band_gender_plot_20-39, fig.height=5, fig.width=9}
age_band_gender_plot <-cvindia::gender_age_band(data = phillipines_data, age_category = "20-39", plot_chart = TRUE)

age_band_gender_plot

```


#Gender and age band 20-39
```{r, age_band_gender_numbers_20-39}
age_band_gender_numbers <- cvindia::gender_age_band(data = phillipines_data, age_category = "20-39", plot_chart = FALSE)

knitr::kable(age_band_gender_numbers)

```

#Gender and age band 40-59

```{r, age_band_gender_plot_40-59, fig.height=5, fig.width=9}
age_band_gender_plot <-cvindia::gender_age_band(data = phillipines_data, age_category = "40-59", plot_chart = TRUE)

age_band_gender_plot

```

#Gender and age band 40-59

```{r, age_band_gender_numbers_40-59}
age_band_gender_numbers <- cvindia::gender_age_band(data = phillipines_data, age_category = "40-59", plot_chart = FALSE)

knitr::kable(age_band_gender_numbers)
```

#Gender and age band 60+

```{r, age_band_gender_plot_60plus, fig.height=5, fig.width=9 }
age_band_gender_plot <-cvindia::gender_age_band(data = phillipines_data, age_category = "60+", plot_chart = TRUE)

age_band_gender_plot

```

#Gender and age band 60+

```{r, age_band_gender_numbers_60plus}
age_band_gender_numbers <- cvindia::gender_age_band(data = phillipines_data, age_category = "60+", plot_chart = FALSE)

knitr::kable(age_band_gender_numbers)
```



# Covid status across symptoms

```{r, covid_status_symptoms_plot, fig.height=5, fig.width=9}

covid_status_symptoms_plo <- cvindia::covid_status_symptoms(data = phillipines_data, start_date= as.Date("2020-04-09"), end_date = as.Date("2020-09-01"), plot_chart = TRUE)
covid_status_symptoms_plo

```



```{r, covid_status_symptoms_numbers}

covid_status_symptoms_numbers <- cvindia::covid_status_symptoms(data = phillipines_data, start_date= as.Date("2020-04-09"), end_date = as.Date("2020-09-01"), plot_chart = FALSE)


covid_status_symptoms_n <- covid_status_symptoms_numbers %>%
  arrange(desc(percentage)) %>% top_n(5)


knitr::kable(covid_status_symptoms_n)
```




```{r, covid_status_comorbidities_plot, fig.height=5, fig.width=9}
covid_status_comorbidities_plot <- cvindia::comorbidities_covid_status(data = phillipines_data, start_date= as.Date("2020-04-09"), end_date = as.Date("2020-09-01"), plot_chart = TRUE)


covid_status_comorbidities_plot

```


```{r,covid_status_comorbidiites_numbers}
covid_status_comorbidities_numbers <- cvindia::comorbidities_covid_status(data = phillipines_data, start_date= as.Date("2020-04-09"), end_date = as.Date("2020-09-01"), plot_chart = FALSE)


covid_st_no <- covid_status_comorbidities_numbers %>%
  arrange(desc(percentage)) %>% top_n(5)

knitr::kable(covid_st_no)

```



# Covid status and gender 

```{r, gender_positive_plot, fig.height=5, fig.width=9}
gender_positive_plot <- cvindia::gender_covid_status(data, covid_status = "positive", plot_chart = TRUE)

gender_positive_plot

```



```{r, gender_positve_numbers}
gender_positive_numbers <- cvindia::gender_covid_status(phillipines_data, covid_status = "positive", plot_chart = FALSE)

knitr::kable(gender_positive_numbers)
```



```{r, gender_showing_symptoms_plot, fig.height=5, fig.width=9}
gender_showsympt_plot <- cvindia::gender_covid_status(data, covid_status = "showing symptoms", plot_chart = TRUE)

gender_showsympt_plot

```



```{r, gender_showing_symptoms_numbers}
gender_showsympt_numbers <- cvindia::gender_covid_status(phillipines_data, covid_status = "showing symptoms", plot_chart = FALSE)

knitr::kable(gender_showsympt_numbers)
```




```{r, gender_negative_plot, fig.height=5, fig.width=9}
gender_negative_plot <- cvindia::gender_covid_status(data, covid_status = "negative", plot_chart = TRUE)

gender_negative_plot

```



```{r, gender_negative_numbers}
gender_negative_numbers <- cvindia::gender_covid_status(phillipines_data, covid_status = "negative", plot_chart = FALSE)

knitr::kable(gender_negative_numbers)

```
