---
title: "R Notebook"
output:
  pdf_document:
    number_sections: yes
    toc: yes
  word_document:
    toc: yes
  html_document:
    df_print: paged
    toc: yes
code_folding: hide
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

library(magrittr)
```



```{r import-data, cache = TRUE, echo=TRUE}

data_select <- readr::read_csv("D:/Rprojects/data/data_select_15052020.csv")

data_map <- readr::read_csv("D:/Rprojects/data/PivotMappe060520r.csv")


```



```{r world-map, echo = F, results='asis', fig.height=5, fig.width=6, cache=TRUE}

# world_map <- cvindia::count_mapp_world(data = data_map, start_date = as.Date("2020-04-09", format = "%Y-%m-%d"), 
#                          end_date = as.Date("2020-05-09", format = "%Y-%m-%d" ), plot_chart = TRUE)
# 
# world_map
```

```{r world-map-numbers, echo = F,  results='asis',  fig.height=5, fig.width=9, cache=TRUE}

# world_map <- cvindia::count_mapp_world(data = data_map, start_date = as.Date("2020-04-09", format = "%Y-%m-%d"), 
#                          end_date = as.Date("2020-05-09", format = "%Y-%m-%d" ), plot_chart = FALSE)
# 
# knitr::kable(world_map)

```



```{r symptoms_covid_in_resp, echo = F, results='asis',  fig.height=5, fig.width=9, cache=TRUE}
symtoms_covid_in_resp <- cvindia::symptom_profile_covid_tested(data = data_select, start_date = as.Date("2020-04-01", format = "%Y-%m-%d"), 
                                           end_date = as.Date("2020-09-01", format = "%Y-%m-%d"), plot_chart = TRUE)
symtoms_covid_in_resp
```


```{r symptoms_covid_in_resp_numbers, echo = F, results='asis',  fig.height=5, fig.width=9, cache=TRUE}
symtoms_covid_in_resp <- cvindia::symptom_profile_covid_tested(data = data_select, start_date = as.Date("2020-04-01", format = "%Y-%m-%d"), 
                                           end_date = as.Date("2020-09-01", format = "%Y-%m-%d"), plot_chart = FALSE)

knitr::kable(dplyr::top_n(symtoms_covid_in_resp, 10), width=1)
```



```{r symptom_profile_all_symptoms, echo = F, results='asis', fig.height=5, fig.width=9, cache=TRUE}
all_syptpms_frequency <- cvindia::symptom_profile_frequency_plot(data = data_select, start_date = as.Date("2020-04-09", format = "%Y-%m-%d"), 
                                            end_date = as.Date("2020-05-09", format = "%Y-%m-%d"),
                                            plot_chart = TRUE)

all_syptpms_frequency

```



```{r symptom_profile_all_symptoms_numbers, echo= F, results='asis',   fig.height=5, fig.width=9, cache=TRUE}
all_syptpms_numbers <- cvindia::symptom_profile_frequency_plot(data = data_select, start_date = as.Date("2020-04-09", format = "%Y-%m-%d"), 
                                            end_date = as.Date("2020-05-09", format = "%Y-%m-%d"),
                                            plot_chart = FALSE)

knitr::kable(dplyr::top_n(all_syptpms_numbers, 10))

```


```{r self-diagnosis, echo=F, results='asis', fig.height=5, fig.width=9, cache=TRUE}
diagn_mild_mod_severe <- cvindia::self_diagnosis_mild_mod_severe(data = data_select, start_date = as.Date("2020-04-09"), end_date = as.Date("2020-05-09"), plot_chart = TRUE, title = "Self Report")

diagn_mild_mod_severe
```


```{r mild_mod_severe,  echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
self_reported <- cvindia::self_diagnosis_mild_mod_severe(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE, title = "Test")


knitr::kable(dplyr::top_n(self_reported, 10))

```

```{r temperature, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
temperature <-  cvindia::temparature_covid_tested(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = TRUE)

temperature
```



```{r temperature_numbers, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
temperature <-  cvindia::temparature_covid_tested(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE)

temperature

```


```{r mild_symptom, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
mild <- cvindia::symptom_profile_mild(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = TRUE)

mild
```



```{r mild_symptom_numbers, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
mild <- cvindia::symptom_profile_mild(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE)

knitr::kable(dplyr::top_n(mild, 10))
```



```{r moderate,echo=FALSE, results='asis', fig.height=5, fig.width=6, cache=TRUE }
moderate <- cvindia::moderate_manifestation_plot(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = TRUE)

moderate
```



```{r moderate-numbers,echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE }
moderate <- cvindia::moderate_manifestation_plot(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE)

knitr::kable(dplyr::top_n(moderate, 10))
```


```{r severe, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
severe <- cvindia::severe_manifestation_plot(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = TRUE)

severe
```


```{r severe-numbers, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
severe <- cvindia::severe_manifestation_plot(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE)

knitr::kable(dplyr::top_n(severe, 10))
```



```{r self_diagnosis, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
self_diagnosis <- cvindia::self_diagnosis_mild_mod_severe(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = TRUE)

self_diagnosis
```



```{r self_diagnosis_numbers, echo=FALSE, results='asis', fig.height=5, fig.width=9, cache=TRUE}
self_diagnosis <- cvindia::self_diagnosis_mild_mod_severe(data = data_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE)

knitr::kable(dplyr::top_n(self_diagnosis, 10))
```


