---
title: "Example of Report, Covid-19, India"
author: "Gabriel Burcea"
date: "r Sys.Date()"
output:
  html_document:
    df_print: paged
  pdf_document: default
vignette: |
  %\VignetteIndexEntry{Vignette Title} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
data <- PivotMappe060520r

library(magrittr)

dt_select <- data %>%
  dplyr::select(ID, Age, Gender, Location, Country, Chills, Cough, Diarrhoea, Fatigue, Headcahe, 'Healthcare Worker', 
                'How Unwell', 'Long Standing Health Issues', 'Loss of smell and taste', 'Muscle Ache', 'Nasal Congestion',                  'Nausea and Vomiting', 'Number Of Days Symptoms Showing', 'Pregnant', 'Self Diagnosis', 'Shortness of Breath',                'Sore Throat', 'Sputum', 'Temperature') %>%
  dplyr::rename( id = ID,
                 age = Age,
                 gender = Gender,
                 location =  Location,
                 country = Country,
                 chills = Chills,
                 diarrhoea = Diarrhoea,
                 fatigue = Fatigue,
                 headache = Headcahe,
                 healthcare_worker = 'Healthcare Worker',
                 how_unwell = 'How Unwell',
                 long_standing_health = 'Long Standing Health Issues',
                 loss_smell_taste = 'Loss of smell and taste',
                 muscle_ache = 'Muscle Ache',
                 nasal_congestion = 'Nasal Congestion',
                 nausea_vomiting = 'Nausea and Vomiting',
                 no_days_symptoms_show = 'Number Of Days Symptoms Showing',
                 pregnant =  'Pregnant',
                 shortness_breath = 'Shortness of Breath',
                 sore_throat = 'Sore Throat',
                 sputum = 'Sputum',
                 temperature = 'Temperature',
                 self_diagnosis = 'Self Diagnosis')
```


```{r respondents-per-country, include=FALSE, fig.height=5, fig.width=7, cache=TRUE}

cvindia::count_mapp_world(data = data, item = "world", start_date = "2020-04-09", end_date = "2020-05-09", plot_chart = TRUE, title= "World Map")


```



```{r setup, include=FALSE}
knitr::kable(cvindia::count_mapp_world(data = data, item = "world", start_date = "2020-04-09", end_date = "2020-05-09", plot_chart = FALSE, title= "World Map"))
```





```{r self-diagnosis, echo=F, results='asis', fig.height=5, fig.width=7, cache=TRUE}
cvindia::count_plot_self_diagnosis(data = dt_select, start_date = as.Date("2020-04-09"), end_date = as.Date("2020-05-09"), 
                                   plot_chart = TRUE, title = "Self Report")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
knitr::kable(self_reported <- cvindia::count_plot_self_diagnosis(data = dt_select, start_date = as.Date("2020-04-09"), 
                                                    end_date = as.Date("2020-05-09"), plot_chart = FALSE, title = "Test"))

```



```{r setup, include=FALSE}


```


```{r setup, include=FALSE}

```




```{r setup, include=FALSE}
```


```{r setup, include=FALSE}
```


```{r setup, include=FALSE}

```


