---
title: "18_08_2020_correlation_matrix"
author: "Gabriel Burcea"
date: "02/09/2020"
output: word_document
---

```{r}

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

library(magrittr)
library(tidyverse)
library(corrplot)
library(qgraph)
```



```{r}

data_cor_mat <- readr::read_csv("/Users/gabrielburcea/rprojects/data/your.md/cleaned_data_18_08_2020_fully_cleaned_uniq_comorb.csv")
```


```{r}

corr_data <- data_cor_mat %>%
  dplyr::select(chills, cough, diarrhoea, fatigue, headache, loss_smell_taste, muscle_ache, nasal_congestion, 
         nausea_vomiting, shortness_breath, sore_throat, sputum, temperature, loss_appetite, chest_pain, itchy_eyes, 
         joint_pain) %>%
  drop_na()

#corr_bin_transf <- ifelse(corr_data == "Yes", 1,0)
options(digits = 2)
correlations <- round(cor_auto(corr_data), 2)
data_viz <- corrplot(correlations, method = "color")
```


From the correlation matrix, it is noticed, fatigue and muscle ache seem to be correlated, but only with 0.43550, the highest correlation. Yet, for the highest correlation, it is not even passing the 0.5. However, I choose to take out of the analysis the fatigue variable. 


```{r}

library(lares)
corr_cross(corr_data, # name of dataset
  max_pvalue = 0.05, # display only significant correlations (at 5% level)
  top = 10 # display top 10 couples of variables (by correlation coefficient)
)
```





