
reason_for_help_level_1 <- c(
  "negative" = "None",                                                                                                                                                                                        
  "showing symptoms" =  "Showing Symptoms But Not Tested",                                                                                                                                                             
  "negative" =  "Self-Isolating With No Symptoms" ,                                                                                                                                                            
  "positive" "Tested Positive" ,                                                                                                                                                                            
  "negative" = "Curious",                           
  "showing symptoms" =  "Tested Negative But Have Symptoms",                                                                                                                                                          
  "showing symptoms"  = "Showing Symptoms But Not Tested,Curious",                                                                                                                                                   
  "showing symtoms" = "Recovered But Have New Symptoms",                                                                                                                                                             
  "showing symptoms !" "Showing Symptoms But Not Tested,Curious,Self-Isolating With No Symptoms",                                                                                                                   
  "negative" =  "Curious,Self-Isolating With No Symptoms",                                                                                                                                                     
  "showing symptoms" =  "Showing Symptoms But Not Tested,Recovered But Have New Symptoms",                                                                                                                            
  "negative" =  "Live With Someone With Coronavirus",                                                                                                                                                     
  "negative" =  "Live With Someone With Coronavirus,Curious",                                                                                                                                                  
  "showing symptoms !" "Tested Negative But Have Symptoms,Self-Isolating With No Symptoms",                                                                                                                        
  "showing symptoms"  = "Recovered But Have New Symptoms,Curious",                                                                                                                                                   
  "showing symptoms"  =  "Tested Negative But Have Symptoms,Curious",                                                                                                                                                   
  "positive !"  =  "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested",                                                                                                         
  "positive" =     "Tested Positive,Self-Isolating With No Symptoms",                                                                                                                                           
  "showing symptoms !"  =  "Showing Symptoms But Not Tested,Self-Isolating With No Symptoms",                                                                                                                             
  "positive !" = "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",                                  
  "showing symptoms" =  "Tested Negative But Have Symptoms,Showing Symptoms But Not Tested",                                                                                                                           
  "showing symptoms"  =   "Tested Negative But Have Symptoms,Live With Someone With Coronavirus",                                                                                                                     
  "positive" =    "Tested Positive,Curious",                                                                                                                                                                   
  "positive"  =    "Tested Positive,Live With Someone With Coronavirus",                                                                                                                                       
  "positive !" =    "Tested Positive,Showing Symptoms But Not Tested",                                                                                                                                            
  "showing symptoms !"  "Tested Negative But Have Symptoms,Curious,Self-Isolating With No Symptoms",                                                                                                                   
  "positive !" "Tested Positive,Tested Negative But Have Symptoms,Recovered But Have New Symptoms",                                                                                                           
  "negative" =  "Live With Someone With Coronavirus,Self-Isolating With No Symptoms",                                                                                                                          
  "positive" =  "Tested Positive,Recovered But Have New Symptoms",                                                                                                                                            
  "negative"  =   "Live With Someone With Coronavirus,Curious,Self-Isolating With No Symptoms",                                                                                                                
  "showing symptoms" =   "Showing Symptoms But Not Tested,Live With Someone With Coronavirus,Recovered But Have New Symptoms",                                                                                          
  "showing symptoms" =  "Showing Symptoms But Not Tested,Recovered But Have New Symptoms,Curious",                                                                                                                     
  "showing symptoms" =   "Recovered But Have New Symptoms,Self-Isolating With No Symptoms",                                                                                                                              
  "showing symptoms"  =   "Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",                                                                                                                     
  "showing symptoms" =  "Showing Symptoms But Not Tested,Live With Someone With Coronavirus,Curious",                                                                                                                 
  "positive !" =  "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Live With Someone With Coronavirus,Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",
   "positive !" =  "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Curious",                                                                                                   
  "positive !"    "Tested Positive,Tested Negative But Have Symptoms",                                                                                                                                         
  "showing symptoms" =  "Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",                                                   
  "showing symptoms" =  "Showing Symptoms But Not Tested,Live With Someone With Coronavirus",                                                                                                                          
  "positive"  = "Tested Positive,Recovered But Have New Symptoms,Curious",                                                                                                                                   
  "showing symptoms"  =  "Tested Negative But Have Symptoms,Live With Someone With Coronavirus,Recovered But Have New Symptoms",                                                                                        
  "showing symptoms" =  "Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Curious"
)
    

reason_for_help_level_2 <- c(
  "negative" = "None",                                                                                                                                                                                        
  "showing symptoms" =  "Showing Symptoms But Not Tested",                                                                                                                                                             
  "negative" =  "Self-Isolating With No Symptoms" ,                                                                                                                                                            
  "positive" "Tested Positive" ,                                                                                                                                                                            
  "negative" = "Curious",                           
  "showing symptoms" =  "Tested Negative But Have Symptoms",                                                                                                                                                          
  "showing symptoms"  = "Showing Symptoms But Not Tested,Curious",                                                                                                                                                   
  "showing symtoms" = "Recovered But Have New Symptoms",                                                                                                                                                             
  "negative !" "Showing Symptoms But Not Tested,Curious,Self-Isolating With No Symptoms",                                                                                                                   
  "negative" =  "Curious,Self-Isolating With No Symptoms",                                                                                                                                                     
  "showing symptoms" =  "Showing Symptoms But Not Tested,Recovered But Have New Symptoms",                                                                                                                            
  "negative" =  "Live With Someone With Coronavirus",                                                                                                                                                     
  "negative" =  "Live With Someone With Coronavirus,Curious",                                                                                                                                                  
  "negative !" "Tested Negative But Have Symptoms,Self-Isolating With No Symptoms",                                                                                                                        
  "showing symptoms"  = "Recovered But Have New Symptoms,Curious",                                                                                                                                                   
  "showing symptoms"  =  "Tested Negative But Have Symptoms,Curious",                                                                                                                                                   
  "negative !"  =  "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested",                                                                                                         
  "positive" =     "Tested Positive,Self-Isolating With No Symptoms",                                                                                                                                           
  "negative !"  =  "Showing Symptoms But Not Tested,Self-Isolating With No Symptoms",                                                                                                                             
  "negative !" = "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",                                  
  "showing symptoms" =  "Tested Negative But Have Symptoms,Showing Symptoms But Not Tested",                                                                                                                           
  "showing symptoms"  =   "Tested Negative But Have Symptoms,Live With Someone With Coronavirus",                                                                                                                     
  "positive" =    "Tested Positive,Curious",                                                                                                                                                                   
  "positive"  =    "Tested Positive,Live With Someone With Coronavirus",                                                                                                                                       
  "showing symptoms !" =    "Tested Positive,Showing Symptoms But Not Tested",                                                                                                                                            
  "showing symptoms !"  "Tested Negative But Have Symptoms,Curious,Self-Isolating With No Symptoms",                                                                                                                   
  "negative !" = "Tested Positive,Tested Negative But Have Symptoms,Recovered But Have New Symptoms",                                                                                                           
  "negative" =  "Live With Someone With Coronavirus,Self-Isolating With No Symptoms",                                                                                                                          
  "positive" =  "Tested Positive,Recovered But Have New Symptoms",                                                                                                                                            
  "negative"  =   "Live With Someone With Coronavirus,Curious,Self-Isolating With No Symptoms",                                                                                                                
  "showing symptoms" =   "Showing Symptoms But Not Tested,Live With Someone With Coronavirus,Recovered But Have New Symptoms",                                                                                          
  "showing symptoms" =  "Showing Symptoms But Not Tested,Recovered But Have New Symptoms,Curious",                                                                                                                     
  "showing symptoms" =   "Recovered But Have New Symptoms,Self-Isolating With No Symptoms",                                                                                                                              
  "showing symptoms"  =   "Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",                                                                                                                     
  "showing symptoms" =  "Showing Symptoms But Not Tested,Live With Someone With Coronavirus,Curious",                                                                                                                 
  "negative !"  =  "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Live With Someone With Coronavirus,Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms", 
  "negative !" =   "Tested Positive,Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Curious",                                                                                                   
  "negative !"  =   "Tested Positive,Tested Negative But Have Symptoms",                                                                                                                                         
  "showing symptoms" =  "Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Recovered But Have New Symptoms,Curious,Self-Isolating With No Symptoms",                                                   
  "showing symptoms" =  "Showing Symptoms But Not Tested,Live With Someone With Coronavirus",                                                                                                                          
  "positive"  = "Tested Positive,Recovered But Have New Symptoms,Curious",                                                                                                                                   
  "showing symptoms"  =  "Tested Negative But Have Symptoms,Live With Someone With Coronavirus,Recovered But Have New Symptoms",                                                                                        
  "showing symptoms" =  "Tested Negative But Have Symptoms,Showing Symptoms But Not Tested,Curious"
)
 